### ISSUE TITLE
m3u: https not properly supported

### ISSUE THREAD

**Issue by voidzero** [karlheyes/icecast-kh#156]
I'm running icecast-kh on port 80 and port 443, have specified multiple `<listen-socket>` statements: first port 80, second port 443 with `<ssl>1</ssl>`.

The problem is that, when I specify port 443 before port 80, the m3u returns something akin to the following:

```
% curl https://listen.noagendastream.com/noagenda.m3u
http://listen.noagendastream.com:443/noagenda
```

This is obviously wrong, it should specify `https://`.

What would be ideal, is if I can choose what URL the m3u file should return. I'd prefer it to return the `https://` version. But for now, I have to specify the `<listen-socket>` on port 80 before port 443, so that the URL is at least correct:

```
% curl https://listen.noagendastream.com/noagenda.m3u
http://listen.noagendastream.com:80/noagenda
```

**Comment by karlheyes** [comment]
you can specify you own m3u file in webroot which will be sent instead of the generated one, that one can have the https in that.

The latest commits I have improve on some of this, the next update will allow for SSL to be detected automatically on the configured ports, no need for SSL.  I'll check into the generation of m3u to make sure the protocol is correct.

karl

**Comment by voidzero** [comment]
Oh, didn't know that about webroot. Do I just place a file there? Or is it something I need to do in the config file. Because in that case I wonder how it works for multiple mounts.

**Comment by voidzero** [comment]
Ah, yes. I see. It's a regular file, placed in the webroot. Easy enough. Thanks!

**Comment by karlheyes** [comment]
this should be resolved by now
