### ISSUE TITLE
relay slow listener on relay mount creation

### ISSUE THREAD

**Issue by mooseh** [karlheyes/icecast-kh#180]
Hi Karl

We are having an odd issue with Icecast 2.4.0-kh3 and i'm wondering if you can help us out,
when we add a new relay mount to our ingest we reload icecast using killall -HUP icecast which does a reload without disconnecting any listeners, in the past this hasn't been an issue but for some odd reason it now connects to the ingest with buffering issues every half a second which sounds terrible.

Is there a way around this?

**Comment by karlheyes** [comment]
it's hard to know from the description what is actually going on there. A buffering issue is typically seen from the player that has a starved data feed, so I would make sure the incoming bitrate on the slave mount point is as expected.  If there is some starvation then that will be below what you expect.  If the issue is that the relay is connecting but if no burst is coming from the master end then you can get a stall/play/stall type of effect.

karl.
