### ISSUE TITLE
Alias 7.html of 7.xsl shows empty stats

### ISSUE THREAD

**Issue by yarik2720** [karlheyes/icecast-kh#187]
I made alias 7.html for file 7.xsl, but it shows empty data, example here: http://noisefm.ru:8000/7.html

Also I found, that shoutcast client trying to get stats not from server root, they are using full path with stream name, for example if streaming url is http://noisefm.ru:8000/play they are asking for http://noisefm.ru:8000/play/7.html

Any solutions?

**Comment by karlheyes** [comment]
not really at the moment. The issue is the extraction of the mountpoint in the link is not handled. You can do an alias of /play/7.html to /7.xsl but there is no mountpoint for the translation.  The only hack is probably auth on /*/7.html triggering a 302 response to a new url with the /7.xsl?mount=/... link, messy really and may not be handled by the client.

karl

**Comment by yarik2720** [comment]
Thanks for answer! 
Can you provide some information how to implement that?

**Comment by karlheyes** [comment]
within a mount block for /*/7.html,  add
``` 
<authentication type="url">
  <option name="listener_add" value="http.....php" />
</authentication
```
The php then returns a 200 OK response with a header such as
Location: http...../7.xsl?mount=/stream

**Comment by yarik2720** [comment]
Thank you
