### ISSUE TITLE
XML Parsing Error

### ISSUE THREAD

**Issue by Dylansqui11** [karlheyes/icecast-kh#207]
When I Try to add more than 2 mount points in icecast kh 2.4.0 kh8, i get a xml parsing error.

**Comment by Dylansqui11** [comment]
I Need more than 2 mount points!!

**Comment by karlheyes** [comment]
A parsing error is not flagged up because of multiple sections like mount, a parsing error is something like a tag missing or misspelt or a /tag missing.   You should see some messages about line numbers typically but if not (libxml2 does have some legacy limits) try xmllint, to verify the actualy xml layout.

karl.

**Comment by Dylansqui11** [comment]
when made another mount point and launched the server before the media client, it worked with 3 mount points. It may be when I first done it, I copied it from icecast 2.4.3 but the other time, I copied one of the already put mounts.
