### ISSUE TITLE
affected by CVE-2018-18820 - buffer overflow in url-auth ?

### ISSUE THREAD

**Issue by marillat** [karlheyes/icecast-kh#235]
I don't know if the kh version is affected by this CVE issue.
See https://seclists.org/oss-sec/2018/q4/122 for details

**Comment by edglazer** [comment]
Looking at the [auth_url.c](https://github.com/karlheyes/icecast-kh/blob/8091762ccce40ec7d59e34bcc223f193fc423a19/src/auth_url.c), line 503 has the code:
` poffset = snprintf (post, sizeof (post),`

which _seems_ to be analogous to the code:
`post_offset += snprintf(post + post_offset,`

identified [in this article](https://lgtm.com/blog/icecast_snprintf_CVE-2018-18820) as the problem code. I'm not very familiar with C, however, and I note that there is no iterator in Karl's code, so his version might not be exploitable in the same way? 

The fix is [shown in this commit](https://lgtm.com/projects/g/xiph/Icecast-Server/rev/081a7974e63fa61b717c2ed96c4bfd21d3e4c866), which I'm including, in the case that it is helpful.

**Comment by karlheyes** [comment]
had a look over the weekend.  I had merged the code for the headers with minor differences but had not completely checked it for the offset bug.  I've committed a fix for that and should be ok.  will need to catch up on other reports before cutting a release.

karl.

**Comment by karlheyes** [comment]
The fix is in the master tree, just not cut as a release. kh10 is affected as the code was merged from the xiph codebase but not verified.  I'll cut a kh11 shortly.

karl

**Comment by VTCAKAVSMoACE** [comment]
Status? This is high-priority for us.

**Comment by karlheyes** [comment]
The original code was merged back in kh8 and subsequently updated by kh11 to include a fix that is similar (different logging) in operation.  Nothing has been changed in that regard since then

karl

**Comment by neginhsobhani** [comment]
Does anyone know if the vulnerability is fixed in the latest version which is 2.4.0.kh22?

**Comment by karlheyes** [comment]
A fix has been in for some time, although back around kh17, the way the POST is created was changed (now a generic mechanism used by different parts of icecast) so not only is that buffer issue not there, but the limitations on the lengths of the POST fields are no longer there.

karl

**Comment by neginhsobhani** [comment]
@karlheyes 
thanks for your response.
