### ISSUE TITLE
Memory usage increased

### ISSUE THREAD

**Issue by DuncanFairley** [karlheyes/icecast-kh#244]
I updated from 2.3.3-kh11 to 2.4.0-kh10 1 month ago. I have less than 1000 listeners at any given time.
Previous to 2.4.0 I would use less than 0.5GB of ram, for years at a time. Mostly mp3 streams, one aac. Since updating, icecast has regularly been using more than 4GB, with virt going over 7GB.  Anything I can to help track down a memory leak?

**Comment by karlheyes** [comment]
hmm, just wondering if there is anything since kh10 that I have done that would explain a memory leak like that.  I can make a build with some memory tracking which could help show what is showing up.  I'm not hearing of anyone else seeing something like that so might be worth tracking down if you want a build like that.

karl

**Comment by karlheyes** [comment]
I've notivd no further updates to subsequent releases causing a problem so Ill assume it's not an issue now. kh14 is up with all known fixes applied.

karl.
