### ISSUE TITLE
Logs do not rotate

### ISSUE THREAD

**Issue by radioboss** [karlheyes/icecast-kh#285]
Specifically, the "access.log" continues to grow. It works sometimes, but sometimes the logs appear to grow, while it should be split at 50KB. I'm not sure, but it seems that logs do not grow larger than 50MB.

Relevant config section:
`    <logging>
        <accesslog>access.log</accesslog>
        <errorlog>error.log</errorlog>
        <loglevel>1</loglevel> 
        <logsize>50</logsize> 
        <logarchive>1</logarchive>
    </logging>`

**Comment by karlheyes** [comment]
looks like the setting of the trigger size was being skipped if below 500k. I have changed it to use 100k as the minimum size even if requested less.  The 50Meg is the default if none is set.

karl

**Comment by radioboss** [comment]
Thank you for clarifying this. What's the point of the minimum size limit? Regular Icecast version allows any log size, so I don't think it makes any sence for KH edition to impose such a limitation.

**Comment by karlheyes** [comment]
imagine setting a 1k cycle, you would hardly get anything on that, probably involving more work to deal with the cycle.   When I rewrote the log system for ic2, there were a whole bunch of things that were not put in place because most sites used large settings or used portals that did that for them. I don't think the xiph build uses a separate thread either but elimates possible stalling cases against certain IO systems.  100k is still fairly small for logging.

Note that the logs can be separately spec'd out eg 
```
<errorlog>
    <name>error.log</name>
    <size>1000000</size>
</errorlog>
```
karl

**Comment by radioboss** [comment]
Thank you for clarification. 100K seems a reasonable size. It would also be a good idea to mention this in the docs somewhere. 
Do you plan on issuing a release with this change anytime soon?

**Comment by karlheyes** [comment]
I'll do a kh14 in the next day or so. I think I've done what tidying needs to be done before then.  Just need to make sure the windows side builds as expected.

karl
