### ISSUE TITLE
on-connect does not work with chroot on

### ISSUE THREAD

**Issue by simon1tan** [karlheyes/icecast-kh#339]
With my config like this:
<on-connect>/mnt/data/src/icecast-kh-icecast-2.4.0-kh15/test/on-connect.sh</on-connect>
<on-disconnect>/mnt/data/src/icecast-kh-icecast-2.4.0-kh15/test/on-disconnect.sh</on-disconnect>
...
<security>
        <chroot>0</chroot>
</security>

both scripts are able to output a test file successfully. When I turn on chroot and use sudo to start icecast, I cannot get the scripts to run. Tried:
<on-connect>on-connect.sh</on-connect>
<on-disconnect>on-disconnect.sh</on-disconnect>
...
<basedir>/mnt/data/src/icecast-kh-icecast-2.4.0-kh15/test</basedir>
<security>
        <chroot>0</chroot>
        <changeowner>
            <user>crazy</user>
            <group>crazy</group>
        </changeowner>
</security>

I expect it to chroot into /mnt/data/src/icecast-kh-icecast-2.4.0-kh15/test where the scripts are located and be able to execute them.
Files belong to user and executable. Any thoughts/advice?

**Comment by karlheyes** [comment]
you can try it manually, chroot in the shell and try to run the scripts.  Failures can be easy with chroot, it is usually because the runtime environment is not set up fully.  eg, is the shell available in the jail? 

chroot  /mnt/data/src/icecast-kh-icecast-2.4.0-kh15/test      /on-connect.sh

karl.

**Comment by simon1tan** [comment]
thanks, I got it working
