### ISSUE TITLE
Problem to return from fallback-mount playback

### ISSUE THREAD

**Issue by ExeEnzo** [karlheyes/icecast-kh#367]
I have 5 different mountpoints on the same port. When the source stream is stopped, icecast plays the "fallback" audio file. But when the source is restored, the 5 mountpoints are no longer in the same order and therefore each mountpoint no longer plays the corresponding source.

**Comment by boteman** [comment]
I discovered the hard way that you need a separate fallback for each mount point so that the fallback knows where it originated. With only one fallback it's a random selection of where it returns to.

In my case on linux I just created one mp3 file with a file system link to each different fallback mount point.

**Comment by karlheyes** [comment]
This is a known issue with fallback mounts.  They are shared so if listeners drop back to them then those listeners could be overridden and re-located elsewhere.

With the kh17 (in pre5) update, I'm introducing a different mechanism. You can connect a source client onto an existing relay without dropping listeners and when that source disconnects, the original relay restarts.   If  you want to relay a file then you can but you need some bitrate specification so it's in real time.   With this, you don't need a fallback and of course a relay can use multiple hosts.
