### ISSUE TITLE
Use Relative Paths on Public Web HTML Files

### ISSUE THREAD

**Issue by BusterNeece** [karlheyes/icecast-kh#379]
Hey there! Quick question: would it be possible for this repo to use relative paths in the HTML files for images/frames/etc?

We very frequently send users to an Icecast installation that _isn't_ at the root of its directory structure, due to being proxied through an nginx proxy to serve on ports 80/443.

We can (and currently do) just replace all the relevant HTML files in our own build step, but it would be really handy if the files bundled with the Icecast distribution just used relative paths directly. In our experimentation, this has no impact whatsoever on the traditional functioning of Icecast when it's at the document root of its own dedicated port, but it enables proxied connections in subfolders to work as expected.

More than happy to PR this in if that would be preferable.

**Comment by gunsar** [comment]
I think it's very possible, because everything is collected in the /web directory and can be directed there. and that's an advantage of icecast-kh that I feel. Even without a nginx proxy, the important thing is that ports 80 and 443 are opened, everything from the /web folder is open for the public, and the contents can be changed at will.

**Comment by BusterNeece** [comment]
Merged!
